### ISSUE TITLE
fix chart

### ISSUE THREAD

**Issue by Indradwi22** [ridnarong/angular-intern#5]
Use this CSS in app.css

``` css
body {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}
.overlay {
  fill: none;
  pointer-events: all;
}

.focus circle {
  fill: none;
}
```
